In [3]:
import numpy as np


In [62]:
#1 

In [63]:
#vektor tek boyutlu matris ise cift boyutlu 

In [64]:
#2

In [66]:
a=np.array([1,3,4,2,3,7,4,5,2,3])
a

array([1, 3, 4, 2, 3, 7, 4, 5, 2, 3])

In [67]:
a.size

10

In [69]:
#3

In [70]:
b=np.full((10,10),0, dtype="int32")
b

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

#4

In [71]:
c=np.full((10,10), 1, dtype="float")
c

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [72]:
#5

In [73]:
d=np.full((10,10),9,dtype="int32")
d

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]], dtype=int32)

In [74]:
#6

In [75]:
np.arange(5,25,3)

array([ 5,  8, 11, 14, 17, 20, 23])

In [76]:
#7

In [77]:
np.linspace(-1,1,30)

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

In [83]:
#8

In [84]:
np.random.randint(0,30,(5,6))

array([[ 2,  4, 15, 10, 15, 10],
       [15, 13, 29, 25,  3,  3],
       [10, 11, 11,  3, 15,  3],
       [ 9, 22, 18,  4,  7, 28],
       [ 7, 23,  0, 26,  0,  3]])

In [78]:
#9

In [79]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [80]:
#10

In [82]:
a=np.random.randint(0,10,(5,10))
a

array([[3, 9, 8, 4, 4, 4, 3, 7, 7, 7],
       [6, 4, 3, 4, 5, 9, 4, 5, 7, 5],
       [0, 3, 1, 5, 6, 1, 7, 2, 2, 8],
       [1, 2, 3, 5, 7, 8, 6, 4, 9, 7],
       [7, 9, 7, 6, 7, 2, 2, 8, 6, 5]])

In [85]:
a.size

50

In [86]:
a.ndim

2

In [87]:
a.shape

(5, 10)

In [88]:
a.dtype

dtype('int64')

In [89]:
#11

In [93]:
np.random.randint(10,size=(3,4,7))


array([[[2, 6, 6, 1, 2, 9, 5],
        [6, 4, 8, 7, 9, 2, 6],
        [5, 6, 5, 7, 3, 4, 1],
        [4, 0, 5, 2, 7, 5, 2]],

       [[3, 4, 2, 9, 1, 7, 6],
        [2, 9, 7, 9, 2, 4, 6],
        [5, 8, 1, 4, 1, 8, 6],
        [9, 4, 9, 3, 5, 8, 6]],

       [[3, 6, 3, 0, 4, 7, 4],
        [5, 2, 3, 9, 0, 2, 2],
        [5, 7, 9, 9, 0, 1, 4],
        [2, 0, 5, 6, 5, 6, 9]]])

In [94]:
#12

In [100]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
#13

In [103]:
a=np.arange(1,5)

b=np.arange(6,10)

c=np.arange(11,15)

d=np.arange(16,20)

In [104]:
np.concatenate([a,b,c,d])

array([ 1,  2,  3,  4,  6,  7,  8,  9, 11, 12, 13, 14, 16, 17, 18, 19])

In [105]:
#14

In [128]:
a=np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [131]:
b=np.random.randint(1,15, (5,5))
b

array([[ 6,  8,  8,  2,  1],
       [11,  4,  7,  7,  8],
       [13, 11,  6,  9,  7],
       [ 8, 14,  3,  9, 10],
       [11,  1, 10,  3,  1]])

In [132]:
np.vstack([a,b])

array([[ 1,  2,  3,  4,  5],
       [ 6,  8,  8,  2,  1],
       [11,  4,  7,  7,  8],
       [13, 11,  6,  9,  7],
       [ 8, 14,  3,  9, 10],
       [11,  1, 10,  3,  1]])

In [133]:
#15

In [1]:
#axis=1 birlestirme islemini yatay (satir) olarak yapar  0 sutun, 1satir
#axis=0 birlestirme islemini dikey (sutun) olarak yapar  1 sutun, 0satir

In [2]:
#16

In [28]:
a = np.array([4, 5, 3,2])

b = np.array([[7, 8, 4,5], 
              [6, 5, 4,3]])

In [29]:
np.vstack([a,b])

array([[4, 5, 3, 2],
       [7, 8, 4, 5],
       [6, 5, 4, 3]])

In [30]:
a = np.array([[91],
              [92]])

b = np.array([[9, 78, 47], 
              [6, 5, 45]])

In [31]:
np.hstack([a,b])

array([[91,  9, 78, 47],
       [92,  6,  5, 45]])

In [40]:
#17

In [34]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.split(a,[2,4,7])

[array([1, 2]), array([3, 4]), array([5, 6, 7]), array([8, 9])]

In [41]:
#18

In [39]:
a=np.random.randint(13,34,(2,10))
a

array([[26, 26, 21, 28, 20, 30, 28, 25, 22, 16],
       [24, 31, 15, 14, 20, 18, 27, 31, 19, 20]])

In [43]:
np.sort(a)

array([[16, 20, 21, 22, 25, 26, 26, 28, 28, 30],
       [14, 15, 18, 19, 20, 20, 24, 27, 31, 31]])

In [45]:
np.argsort(a)

array([[9, 4, 2, 8, 7, 0, 1, 3, 6, 5],
       [3, 2, 5, 8, 4, 9, 0, 6, 1, 7]])

In [50]:
#19

In [48]:
a=np.random.randint(30,size=20)
a

array([10, 20, 13, 18, 14, 21,  2, 29, 10, 10, 14, 27, 17, 27,  4, 16, 26,
       25,  5, 21])

In [94]:
a[3],a[5],a[7]

(18, 15, 0)

In [51]:
#20

In [91]:
a=np.random.randint(20,size=10)
a

array([ 1,  5, 16, 18,  0, 15, 15,  0,  4,  0])

In [92]:
a[4]=10

In [93]:
a

array([ 1,  5, 16, 18, 10, 15, 15,  0,  4,  0])

In [56]:
#21

In [57]:
#In linear algebra, a diagonal matrix is a matrix in which the entries outside the main diagonal are all zero; the term usually refers to square matrices. 
#Definition Let A be a $K imes K$ matrix. Then, its trace, denoted by [eq1] or [eq2], is the sum of its diagonal elements:

In [58]:
#22

In [62]:
a = np.zeros((5, 5), int)
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [65]:
np.fill_diagonal(a, [4,3,2,5,4])
a

array([[4, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 4]])

In [67]:
a[0,0], a[1,1],a[2,2],a[3,3],a[4,4]

(4, 3, 2, 5, 4)

In [68]:
#23

In [71]:
a=np.arange(10,21)
a[3::]

array([13, 14, 15, 16, 17, 18, 19, 20])

In [72]:
#24

In [110]:
a=np.random.randint(0,10, size=(10,10))
a

array([[3, 4, 6, 6, 7, 3, 3, 7, 3, 1],
       [1, 1, 2, 1, 0, 0, 5, 1, 7, 6],
       [2, 7, 0, 3, 8, 3, 1, 7, 9, 8],
       [1, 3, 9, 5, 4, 3, 7, 4, 3, 2],
       [0, 1, 9, 5, 2, 7, 4, 8, 5, 7],
       [4, 8, 8, 8, 5, 0, 6, 4, 0, 0],
       [9, 5, 0, 8, 3, 7, 1, 9, 4, 8],
       [2, 2, 1, 9, 4, 3, 3, 9, 9, 8],
       [0, 0, 1, 2, 6, 3, 8, 1, 4, 4],
       [9, 8, 1, 9, 6, 9, 9, 8, 9, 7]])

In [111]:
a[3,5], a[:,5] , a[2,:], a[2:7,:] , a[2:5,3:7], a[::5,4::]

(3,
 array([3, 0, 3, 3, 7, 0, 7, 3, 3, 9]),
 array([2, 7, 0, 3, 8, 3, 1, 7, 9, 8]),
 array([[2, 7, 0, 3, 8, 3, 1, 7, 9, 8],
        [1, 3, 9, 5, 4, 3, 7, 4, 3, 2],
        [0, 1, 9, 5, 2, 7, 4, 8, 5, 7],
        [4, 8, 8, 8, 5, 0, 6, 4, 0, 0],
        [9, 5, 0, 8, 3, 7, 1, 9, 4, 8]]),
 array([[3, 8, 3, 1],
        [5, 4, 3, 7],
        [5, 2, 7, 4]]),
 array([[7, 3, 3, 7, 3, 1],
        [5, 0, 6, 4, 0, 0]]))

In [112]:
b=a.copy()
b

array([[3, 4, 6, 6, 7, 3, 3, 7, 3, 1],
       [1, 1, 2, 1, 0, 0, 5, 1, 7, 6],
       [2, 7, 0, 3, 8, 3, 1, 7, 9, 8],
       [1, 3, 9, 5, 4, 3, 7, 4, 3, 2],
       [0, 1, 9, 5, 2, 7, 4, 8, 5, 7],
       [4, 8, 8, 8, 5, 0, 6, 4, 0, 0],
       [9, 5, 0, 8, 3, 7, 1, 9, 4, 8],
       [2, 2, 1, 9, 4, 3, 3, 9, 9, 8],
       [0, 0, 1, 2, 6, 3, 8, 1, 4, 4],
       [9, 8, 1, 9, 6, 9, 9, 8, 9, 7]])

In [113]:
b[5,5]=1984
b

array([[   3,    4,    6,    6,    7,    3,    3,    7,    3,    1],
       [   1,    1,    2,    1,    0,    0,    5,    1,    7,    6],
       [   2,    7,    0,    3,    8,    3,    1,    7,    9,    8],
       [   1,    3,    9,    5,    4,    3,    7,    4,    3,    2],
       [   0,    1,    9,    5,    2,    7,    4,    8,    5,    7],
       [   4,    8,    8,    8,    5, 1984,    6,    4,    0,    0],
       [   9,    5,    0,    8,    3,    7,    1,    9,    4,    8],
       [   2,    2,    1,    9,    4,    3,    3,    9,    9,    8],
       [   0,    0,    1,    2,    6,    3,    8,    1,    4,    4],
       [   9,    8,    1,    9,    6,    9,    9,    8,    9,    7]])

In [114]:
#25

In [117]:
a=np.arange(0,51,5)

In [119]:
np.sum(a>20),np.sum(a<30), np.sum(a==33)

(6, 6, 0)

In [ ]:
import numpy as np
i=0
while True:
    

    a=np.random.random((2,2))
    b=np.random.random((2,2))
    c=a-b
    d=np.diagonal(c)
    if np.any(d<0.1)=="False" and np.any(d>-0.1)=="False":
        print("{}. denemede buldunuz".format(i+1))
        quit()
    else:
        i+=1
        continue
        

